### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by androgeninc** [wiltonsr/Flask-Toastr#2] opened 2019-08-18 00:37 UTC
Thank you for making this available.

Is there any way i can change the format of the toasts (text color, background color etc)? 

it seems the default is white background with very light grey text. With the opacity and a white background behind the toast, it becomes impossible to see the content of the toast.

**Comment by wiltonsr** [comment] 2019-08-18 01:45
Hi @androgeninc,

All toastr styles come from the .css file, as can be seen [here](https://github.com/wiltonsr/Flask-Toastr/blob/3da264030313495340cf647eadb286e84cbeec56/flask_toastr.py#L22) .

You can override this styles. For example, adding this to your `head` section, you will have toasts's text color in black:

```html
<style>
    #toast-container>div{
        color: black;
    }
</style>
```

Since this is the expected behavior, I will close the issue.

**Closed as completed** 2019-08-18 01:47 UTC
